export const en = {
  // Original translation keys
  appName: "KUFULULA",
  heroBadge: "Free Trade & Escrow Public Workspace",
  heroTitle: "The Marketplace the World Awaited. Trade Without Limits. One World. One platform.",
  heroSub: "Buy safely backed by our multi-rail Mobile Money escrow protocol and instant face verification.",
  searchPlaceholder: "Search by keyword, Lens image match, or QR Code...",
  categoryAll: "All Collections",
  categoryElectronics: "Electronics",
  categoryFood: "Groceries",
  categoryFashion: "Fashion Isolele",
  categoryHome: "Home utilities",
  categoryBooks: "Books & Comics",
  noProductFound: "No available matching products found.",
  noProductSub: "Adjust filter query or launch camera / voice translation helper.",
  cartTitle: "Your Shopping Bag",
  addToCart: "Add to Bag",
  buyNow: "Checkout securely",
  negotiate: "Haggle",
  share: "Share",
  like: "Like",
  comment: "Comment",
  commentsTitle: "Real Community Discussions",
  writeComment: "Post an honest review...",
  postComment: "Comment",
  colorSelect: "Choose product color:",
  angleSelect: "Viewport Angle:",
  specifications: "Technical Specs sheet",
  vendorLabel: "Certified Vendor",
  stockLabel: "Available in stock",
  priceLabel: "Direct Pricing",
  escrowBadge: "Guaranteed Mobile Money Escrow",
  escrowActiveBadge: "Escrow enabled",
  escrowStatusSecured: "Funds secured",
  kycVerificationRequired: "Instant KYC confirmation required to disburse",
  backToShop: "Return to Catalog",
  settingsTitle: "Design Parameters & Experience",
  themeSelect: "Interface Custom Skin",
  fontSelect: "Typography style",
  currencyToggle: "Toggle rate converter",
  adminPortal: "Administrative Panel",
  voiceSearchListen: "Listening to query... State desired item out loud",
  voiceSearchStop: "Processing audio with AI model...",
  lensTitle: "Google Lens & Artificial Intelligence",
  lensScan: "Align product photo or upload an image to identify it instantly with AI...",
  negotiationTitle: "Price Negotiation & Counter-offer",
  negotiateSubmit: "Propose purchase price",
  negotiateCounter: "Merchant response",

  // Navigation
  navHome: "Home",
  navAbout: "About Us",
  navWorks: "Our Works & Comics",
  navImpact: "Impact & Foundation",
  navAwards: "Awards",
  navContact: "Contact",

  // Hero Section
  heroAuthorTitle: "H.R.M. KING KUFULULA",
  heroAuthorSub: "The Visionary Redefining the African Narrative",
  heroQuote: "The story of Africa must no longer be told by others. We forge our own narratives to enlighten the world and inspire future generations.",
  heroSlogan: "Rediscovering our authentic heritage, celebrating our nobility, and building a limitless future through the power of words and visual arts.",
  btnDiscoverWorks: "Discover Literary Works",
  btnJoinFoundation: "Join the We Love Congo Foundation",

  // About Section
  aboutTitle: "An Inspiring Cultural and Panafrican Leader",
  aboutDesc1: "His Royal Majesty King Kufulula (HRM King Kufulula) is the founder of the prestigious platform Isolele. An exceptional storyteller, writer, and guardian of traditions, he dedicates his life to reshaping the global perception of African culture. As a Prince of the Pindi people and a pan-African leader based in the United States, he builds an unbreakable bridge between ancestral history and digital modernity.",
  aboutMissionTitle: "The Isolele Mission",
  aboutMissionDesc: "To project the richness, myths, values, and sovereign narratives of Africa through immersive comic books, graphic novels, and cinematic works of global quality.",
  aboutResilienceTitle: "Resilience as a Legacy",
  aboutResilienceDesc: "A journey shaped by perseverance, turning obstacles and limitations into a language of strength, dignity, and collective compassion.",

  // Literary Works
  worksTitle: "Complete Literary Works",
  work1Title: "1. ZAIÏRE : The Prince of Kongo and the Necklace of Destiny",
  work1Type: "Type: Graphic Novel / Fantasy Epic",
  work1Desc: "A spectacular odyssey that takes root in the beating heart of Kinshasa and expands to the edges of ancient mystical kingdoms. This masterpiece explores the power of a sacred necklace holding the secrets of the African life force. A major work acclaimed for its faithfulness to ancestral spiritual values and traditional attire.",
  work2Title: "2. WOLF OF CONGO: The Prince of Kinshasa",
  work2Type: "Type: Literary Memoir / Story of Life and Leadership",
  work2Desc: "A poignant immersion into the childhood and journey of Arnold Kufulula. Raised far from palace luxuries, amidst the harsh realities of poverty, this book reveals how discipline, patience in the face of systemic delays, and integrity can guide a man toward fulfilling his royal and humanitarian destiny.",

  // Impact Section
  impactTitle: "Humanitarian Impact & Foundation",
  impactSubtitle: "\"We Love Congo\" Foundation",
  impactIntro: "Change is not limited to written stories; it is engraved in daily actions. Through his non-profit organization, King Kufulula actively engages on the ground:",
  impact1Title: "Support for Victims",
  impact1Desc: "Direct assistance to individuals affected by conflicts in the eastern region of the Democratic Republic of the Congo.",
  impact2Title: "Empowerment",
  impact2Desc: "Education programs, skills training, and rehabilitation to enable local communities to thrive independently.",
  impact3Title: "Emergence",
  impact3Desc: "Providing youth with role models so they can believe in their creative and entrepreneurial potential.",

  // Awards Section
  awardsTitle: "Awards & Recognitions",
  award1: "Indusa African Excellence (2025) | Celebrating cultural excellence and pan-African leadership.",
  award2: "My New York Magazine Feature (2025) | International recognition of the impact of the Isolele ecosystem.",
  award3: "Focus Congo Peace Maker (2024) | Award honoring concrete actions for peace and community well-being.",
  award4: "International Father’s Association (2023) | Tribute to family values, mentorship, and benevolence.",

  // Contact
  contactTitle: "Join the African Cultural Renaissance",
  fieldFullName: "Full Name / Institution",
  fieldEmail: "Professional Email Address",
  fieldMessage: "Message / Partnership Intent",
  fieldSubmit: "Submit Partnership Request",
  footerText: "© 2026 Kufulula & Isolele Ecosystem. All rights reserved.",
  footerPower: "Powered by the passion of Africa. Proudly connected to Bukavu, Kinshasa, and the world."
};
