export const kg = {
  // Original translation keys
  appName: "KUFULULA",
  heroBadge: "Kisika ya Bumbote ya Mumbongo ne Mboko-Lukonku",
  heroTitle: "Soko yayi nza yasilanga kingalula. Kudisoba na kisika yampasi. Nza Mosi. Lukalu Luyantika Lulel.",
  heroSub: "Somba na kiyungulu na mindondo te na nzela ya escrow ya Mobile Money.",
  searchPlaceholder: "Luka biloko na ngogo, picha ya Lens, to ne Code QR...",
  categoryAll: "Biloko nionso kiese",
  categoryElectronics: "Kura na Masini",
  categoryFood: "Bilia ya Kolia",
  categoryFashion: "Lilangwa ya Liputa",
  categoryHome: "Biloko ya Ndako",
  categoryBooks: "Mikanda ya Biteke",
  noProductFound: "Eloko moko te emonani na motango.",
  noProductSub: "Bongisa lifiltre to sala kosalela na mongongo to foti ya fono.",
  cartTitle: "Kapo nayo ya Bosombi",
  addToCart: "Bakisa na Kapo",
  buyNow: "Somba Sikoyo na Kimia",
  negotiate: "Meka Talo",
  share: "Kabola na baninga",
  like: "Linga eloko",
  comment: "Tia Liloba",
  commentsTitle: "Malamu ya Bato nionso ya mboka",
  writeComment: "Koma likambo ya bosembo...",
  postComment: "Tia likambo",
  colorSelect: "Pona langi ya eloko :",
  angleSelect: "Liko kotala :",
  specifications: "Biyekoli ya Mozindo",
  vendorLabel: "Moteki ya bosembo",
  stockLabel: "Motango ya motako",
  priceLabel: "Talo ya nka",
  escrowBadge: "Escrow ya Mobile Money na Kimia",
  escrowActiveBadge: "Botia-motema ezali",
  escrowStatusSecured: "Mbongo ebatelami",
  kycVerificationRequired: "Kotala elongi KYC ya nka ezali na tina",
  backToShop: "Zonga na motango",
  settingsTitle: "Boponi ya elongi ya l'application",
  themeSelect: "Langi ya Langi",
  fontSelect: "Lolenge ya kokoma",
  currencyToggle: "Bongola mbongo",
  adminPortal: "Bokonzi ya Molongi",
  voiceSearchListen: "Azali koyoka yo... Loba eloko olingi kosomba",
  voiceSearchStop: "Intelligence Artificielle azali kotala audio...",
  lensTitle: "Google Lens & Intelligence Artificielle",
  lensScan: "Tia picha ya eloko mpo kura ekanga na nswalu na msaada ya IA...",
  negotiationTitle: "Koloba talo na moteki ya biloko",
  negotiateSubmit: "Kopesa talo na ngai",
  negotiateCounter: "Liloba ya moteki",

  // Navigation
  navHome: "Luyantikilu",
  navAbout: "Mu mambu meto",
  navWorks: "Bisalu bieto misono",
  navImpact: "Nsadisa ne Kimvuka",
  navAwards: "Nsendo ye Matoko",
  navContact: "Kinsololo",

  // Hero Section
  heroAuthorTitle: "MFUMLU KUFULULA",
  heroAuthorSub: "Mfumu wa mbono udi uvutula mpa mu mambu ma nza ya Afrika",
  heroQuote: "Mambu ma nza ya Afrika ka mafueti te kulondwa kua bawu kunkulu. Beto mosi tufueti soneka masolo meto mu kutanga nza ye kupesa bana baleke ngangu zambote.",
  heroSlogan: "Kusola diaka mambu ma bankulu beto, kuzitisa kintinu kieto, ye kutunga luzingu lua lumbu ke luiza luena nkalu ku ngolo ya mambu ye nkadilu ya biteke.",
  btnDiscoverWorks: "Monana Mikanda ya Nzitusu",
  btnJoinFoundation: "Kota mu Kimvuka kia We Love Congo",

  // About Section
  aboutTitle: "Mfumu ya Nkadilu udi upesa Ngemba ye Ngolo",
  aboutDesc1: "Mfumu Kufulula (HRM King Kufulula) i ntwadi ya luyalu lua nene lua Isolele. Nsoniki ya mambu ya nene, ntaniri ya mambu ma bankulu, udi upesa luzingu luandi mu kusoba nkadilu udi nza itala mambu ma Afrika. Mutinu muana ya Pindi ye mfumu ya nza ya Afrika udi mu nza ya Amerike, udi utunga mpa ya ngolo muna mambu ma bankulu ye mambu ma kisalu kia mpa kia ordinatere.",
  aboutMissionTitle: "Kisalu kia Isolele",
  aboutMissionDesc: "Kutumbisa mvwama, masolo ma nzambi, bikadilu ye mambu ma kintinu mu Afrika mu mikanda ya biteke ye bisalu bia nene mu nza ya mvimba.",
  aboutResilienceTitle: "Luzingu lua Kukanga Ntimu",
  aboutResilienceDesc: "Nzyungulukulu ya luzingu mu ngolo ya luvunu, kusoba mambu ma mpasi mu nkadilu ya ngolo, kintinu ye nsadisa mu bantu bansoni.",

  // Literary Works
  worksTitle: "Mikanda ya Mvimba ya Nzitusu",
  work1Title: "1. ZAIÏRE : Mfumu muana ya Kongo ye Nlungu ya Lufuanu",
  work1Type: "Nkadilu: Mukanda ya Biteke / Nsololo ya Kimfumu",
  work1Desc: "Nzyungulukulu ya nene udi uyantika mu ntimu ya Kinshasa mu kuenda diaka mu mafumu ma bankulu ma mimpasi. Kisalu eki kitalanga ngolo ya nlungu ya nlongo udi nsimu wa ngolo ya luzingu mu Afrika. Kisalu ya nene ya batoko mu mambu ma kinsisikulu ya bankulu.",
  work2Title: "2. WOLF OF CONGO : Mfumu muana ya Kinshasa",
  work2Type: "Nkadilu: Mukanda ya luzingu / Disolo ya luzingu ye Kintinu",
  work2Desc: "Kikotelo mu kileke ye luzingu lua Arnold Kufulula. Sansi kua kule mu nzo ya kimfumu, mu mpasi ya kinsukami, mukanda ewu udi uleza nkadilu ya mikenji, kukanga ntimu mu mambu ma kzingu ye nkadilu ya mpa udi ntwadi muntu mu kulungisa mambu ma kimfumu ye nsadisa ya bantu.",

  // Impact Section
  impactTitle: "Nsadisa ya Bantu ye Kimvuka kia Luse",
  impactSubtitle: "Kimvuka \"We Love Congo\"",
  impactIntro: "Nsobolo ka yena kaka muna mikanda miasonekwa te; yena muna mambu ma fuku ye fuku. Muna kimvuka kiandi kia luse, Mfumu Kufulula usalanga ngolo :",
  impact1Title: "Nsadisa mu bawu bafuidi",
  impact1Desc: "Nsadisa ya bima ye nzimbu mu bantu bafuanu mu mvita muna Est ya RDC.",
  impact2Title: "Ngolo ya Baleke",
  impact2Desc: "Mambu ma nzo ya kulonguka, dilongi dia bisalu bia maboko mu bantu mu diambu bawu mosi basala.",
  impact3Title: "Ntelama",
  impact3Desc: "Kupesa baleke mbandu zambote mu kwikila mu ngolo zawu za kusala mambu mambote.",

  // Awards Section
  awardsTitle: "Nsendo ye Matoko",
  award1: "Indusa African Excellence (2025) | Matoko ma mvwama ya kinsisikulu ye kintinu mu Afrika.",
  award2: "My New York Magazine Feature (2025) | Nzitusu ya nza ya mvimba mu kisalu kia Isolele.",
  award3: "Focus Congo Peace Maker (2024) | Nsendo ya nzitusu mu kisalu kia ngemba mu bantu.",
  award4: "International Father’s Association (2023) | Zitisa mambu ma nzo ye nkadilu ya mbotika.",

  // Contact
  contactTitle: "Kotani muna Ntelama ya Mvwama ya Afrika",
  fieldFullName: "Nkumbu ya Mvimba / Kimvuka",
  fieldEmail: "Email ya Kisalu",
  fieldMessage: "Nsoniki / Lukanu lua kusala bimosi",
  fieldSubmit: "Tuma Lukanu lua wanyi nsoniki",
  footerText: "© 2026 Kufulula & Isolele Ecosystem. Mambu mansoni malundwa.",
  footerPower: "Muenza mu zola kia Afrika. Mu Bukavu, Kinshasa ye nza ya mvimba."
};
