export const ln = {
  appName: "KUFULULA",
  heroBadge: "Esika ya Bopeto ya Bobandi & Botia-Motema",
  heroTitle: "Soko oyo Mokili ezalaki kozela. Échangez Sans Limites. Mokili moko. Platforme moko.",
  heroSub: "Somba na kiyungulu na mindondo te na nzela ya escrow ya Mobile Money.",
  searchPlaceholder: "Luka biloko na mongongo to na foti na bilili...",
  categoryAll: "Biloko nionso",
  categoryElectronics: "Kura na Masini",
  categoryFood: "Bilia ya Kolia",
  categoryFashion: "Fashion Isolele",
  categoryHome: "Biloko ya Ndako",
  categoryBooks: "Mikanda ya Biteke",
  noProductFound: "Eloko moko te emonani na motango.",
  noProductSub: "Bongisa lifiltre to sala kosalela na mongongo to foti ya fono.",
  cartTitle: "Kapo nayo ya Bosombi",
  addToCart: "Bakisa na Kapo",
  buyNow: "Somba Sikoyo na Kimia",
  negotiate: "Meka Talo",
  share: "Kabola na baninga",
  like: "Linga eloko",
  comment: "Tia Liloba",
  commentsTitle: "Malamu ya Bato nionso ya mboka",
  writeComment: "Koma likambo ya bosembo...",
  postComment: "Tia likambo",
  colorSelect: "Pona langi ya eloko :",
  angleSelect: "Liko kotala :",
  specifications: "Biyekoli ya Mozindo",
  vendorLabel: "Moteki ya bosembo",
  stockLabel: "Motango ya motako",
  priceLabel: "Talo ya nka",
  escrowBadge: "Escrow ya Mobile Money na Kimia",
  escrowActiveBadge: "Botia-motema ezali",
  escrowStatusSecured: "Mbongo ebatelami",
  kycVerificationRequired: "Kotala elongi KYC ya nka ezali na tina",
  backToShop: "Zonga na motango",
  settingsTitle: "Boponi ya elongi ya l'application",
  themeSelect: "Langi ya Langi",
  fontSelect: "Lolenge ya kokoma",
  currencyToggle: "Bongola mbongo",
  adminPortal: "Bokonzi ya Molongi",
  voiceSearchListen: "Azali koyoka yo... Loba eloko olingi kosomba",
  voiceSearchStop: "Intelligence Artificielle azali kotala audio...",
  lensTitle: "Google Lens & Intelligence Artificielle",
  lensScan: "Tia foti ya eloko mpo kura ekanga...",
  negotiationTitle: "Koloba talo na moteki ya biloko",
  negotiateSubmit: "Kopesa talo na ngai",
  negotiateCounter: "Liloba ya moteki",

  // Navigation
  navHome: "Accueil",
  navAbout: "À Propos",
  navWorks: "Nos Œuvres & BD",
  navImpact: "Impact & Fondation",
  navAwards: "Distinctions",
  navContact: "Contact",

  // Hero Section
  heroAuthorTitle: "S.M. LE ROI KUFULULA",
  heroAuthorSub: "Le Visionnaire qui Redéfinit le Récit Africain",
  heroQuote: "L'histoire de l'Afrique ne doit plus être racontée par d'autres. Nous forgeons nos propres récits pour éclairer le monde et inspirer les générations futures.",
  heroSlogan: "Redécouvrir notre héritage authentique, célébrer notre noblesse et bâtir un avenir sans limites à travers la puissance des mots et des arts visuels.",
  btnDiscoverWorks: "Découvrir les Œuvres Littéraires",
  btnJoinFoundation: "Rejoindre la Fondation We Love Congo",

  // About Section
  aboutTitle: "Un Leader Culturel et Panafricaniste Inspira",
  aboutDesc1: "Sa Majesté le Roi Kufulula (HRM King Kufulula) est le fondateur de la prestigieuse plateforme Isolele. Conteur d'exception, écrivain et gardien des traditions, il consacre sa vie à remodeler la perception culturelle de l'Afrique sur la scène mondiale. En tant que Prince des Pindi et leader panafricain basé aux États-Unis, il jette un pont indéfectible entre l'histoire ancestrale et la modernité numérique.",
  aboutMissionTitle: "La Mission Isolele",
  aboutMissionDesc: "Propulser la richesse, les mythes, les valeurs et les récits souverains de l'Afrique à travers des bandes dessinées immersives, des romans graphiques et des œuvres cinématographiques de qualité internationale.",
  aboutResilienceTitle: "La Résilience en Héritage",
  aboutResilienceDesc: "Un parcours façonné par la persévérance, transformant les obstacles et les limitations en un langage de force, de dignité et de compassion collective.",

  // Literary Works
  worksTitle: "Œuvres Littéraires Complètes",
  work1Title: "1. ZAIÏRE : Le Prince du Kongo et le Collier du Destin",
  work1Type: "Type : Roman Graphique / Épopée Fantastique",
  work1Desc: "Une odyssée spectaculaire qui prend racine au cœur battant de Kinshasa pour s'étendre aux confins des royaumes mystiques anciens. Ce chef-d'œuvre explore le pouvoir d'un collier sacré détenant les secrets de la force vitale africaine. Une œuvre majeure saluée pour sa fidélité aux valeurs spirituelles ancestrales et sa mise en valeur des parures traditionnelles.",
  work2Title: "2. WOLF OF CONGO : Le Prince de Kinshasa",
  work2Type: "Type : Mémoire Littéraire / Récit de Vie et de Leadership",
  work2Desc: "Une immersion poignante dans l'enfance et le parcours d'Arnold Kufulula. Élevé loin du faste des palais, au milieu des dures realities de la pauvreté, ce livre dévoile comment la discipline, la patience face aux retards systémiques et l'intégrité peuvent guider un homme vers l'accomplissement de sa destinée royale et humanitaire.",

  // Impact Section
  impactTitle: "Impact Humanitaire & Fondation",
  impactSubtitle: "Fondation \"We Love Congo\"",
  impactIntro: "Le changement ne se limite pas aux histoires écrites ; il s'inscrit dans les actions quotidiennes. À travers son organisation à but non lucratif, le Roi Kufulula s'engage activement sur le terrain :",
  impact1Title: "Soutien aux Victimes",
  impact1Desc: "Assistance directe aux personnes touchées par les conflits à l'Est de la République Démocratique du Congo.",
  impact2Title: "Autonomisation",
  impact2Desc: "Programmes d'éducation, d'apprentissage des métiers et de réhabilitation pour permettre aux communautés locales de prospérer de manière autonome.",
  impact3Title: "Émergence",
  impact3Desc: "Offrir aux jeunes des repères pour qu'ils croient en leur potentiel créatif et entrepreneurial.",

  // Awards Section
  awardsTitle: "Palmarès & Distinctions",
  award1: "Indusa African Excellence (2025) | Célébration de l'excellence culturelle et du leadership panafricain.",
  award2: "My New York Magazine Feature (2025) | Reconnaissance internationale de l'impact de l'écosystème Isolele.",
  award3: "Focus Congo Peace Maker (2024) | Prix honorant les actions concrètes en faveur de la paix et du bien-être des populations.",
  award4: "International Father’s Association (2023) | Hommage aux valeurs familiales, à la transmission et à la bienveillance.",

  // Contact
  contactTitle: "Rejoignez la Renaissance Culturelle Africaine",
  fieldFullName: "Nom Complet / Institution",
  fieldEmail: "Adresse Email Professionnelle",
  fieldMessage: "Message / Intention de Partenariat",
  fieldSubmit: "Envoyer ma demande",
  footerText: "© 2026 Kufulula & Isolele Ecosystem. Tous droits réservés.",
  footerPower: "Propulsé par la passion de l'Afrique. Fièrement connecté à Bukavu, Kinshasa et au monde."
};
