export const lu = {
  // Original translation keys
  appName: "KUFULULA",
  heroBadge: "Mbuilu wa Bianda ne Kudisungila kua Diatamba",
  heroTitle: "Soko didi ba pa buloba muindile. Shintululaye kabuyi mupaka. Buloba Bumo. Ndongamenu Imo.",
  heroSub: "Sumba mianya ne butekemenu buonso mu diambuluisha dia escrow ya Mobile Money.",
  searchPlaceholder: "Keba bintu ne miaku, picha ya Lens, to ne Code QR...",
  categoryAll: "Bintu Bionso mutupu",
  categoryElectronics: "Mashinyi ne Diambuluisha",
  categoryFood: "Biakudia bia ditunda",
  categoryFashion: "Bilamba bia kapia",
  categoryHome: "Nzubilu ne Bilamba",
  categoryBooks: "Mikanda ne Bimfuanyi IP",
  noProductFound: "Kakuena eloko mimonike mu liste to.",
  noProductSub: "Keba bikuabo bintu to munda mua foti to ne diyi.",
  cartTitle: "Tshisaku tshebe tshia Manunza",
  addToCart: "Ela mu tshisaku",
  buyNow: "Sumba ne ditalala",
  negotiate: "Yukidila Talo",
  share: "Kabola bionso bionso",
  like: "Linga eloko",
  comment: "Akula tshinyi",
  commentsTitle: "Malu mimonika kundi ku bantu",
  writeComment: "Funda malu a jiji...",
  postComment: "Ela diyi",
  colorSelect: "Sola nkuluka ya bintu :",
  angleSelect: "Kutangila kua mianya :",
  specifications: "Mukanda wa Bipapu bionso",
  vendorLabel: "Muledi mupishibue",
  stockLabel: "Bintu bishaleko",
  priceLabel: "Ditala talo",
  escrowBadge: "Escrow ya Mobile Money ifidibue ne Kimia",
  escrowActiveBadge: "Diyemena didiko",
  escrowStatusSecured: "Mfalanga miaba misungidibue",
  kycVerificationRequired: "Kutangila mianya ya elongi KYC ne muenji",
  backToShop: "Pinganaye mu tshisumbu",
  settingsTitle: "Dilongolola dia visual ya web",
  themeSelect: "Langi ya Nzubilu",
  fontSelect: "Mushindu wa mufundilu",
  currencyToggle: "Shintulula lupolo",
  adminPortal: "Lubanza lua Batatabi",
  voiceSearchListen: "Teleja diyi lusezo... Akulaye eloko mudi usumba",
  voiceSearchStop: "Intelligence Mnemba utangila diyi...",
  lensTitle: "Google Lens & Intelligence Artificielle",
  lensScan: "Tia picha ya eloko to ela faili bua kumona eloko ewu ne bushuwa ne diambuluisha dia IA...",
  negotiationTitle: "Muyukidilu wa Talo ne ofe wa muledi",
  negotiateSubmit: "Fila talo wanyi mudiko",
  negotiateCounter: "Andamina wa muteki",

  // Navigation
  navHome: "Kutwshila",
  navAbout: "Bualu buetu",
  navWorks: "Mikanda ne Bimfuanyi bietu",
  navImpact: "Diambuluisha ne Bulongolodi",
  navAwards: "Bifumu ne Netu",
  navContact: "Diyukidilangana",

  // Hero Section
  heroAuthorTitle: "MFUMLU KUFULULA",
  heroAuthorSub: "Mumonyi wa malu kumpala udi wakaja kabidi miand ya mu Afrika",
  heroQuote: "Muanda wa munda mua Afrika kawena muanji kulondwa kudi bende to. Tudi tuenza mianda yetu nkayetu bua kukenzesha buloba ne kupesha bansonga lungenyi luimpe.",
  heroSlogan: "Kusanganulula bumpianyi buetu bulelela, kutumbisha buneme buetu, ne kuibaka matuku adi alua broken mupaka ku diambuluisha dia ngakuilu ne bimfuanyi bia luse.",
  btnDiscoverWorks: "Sanganulula Mikanda ya Utumbishi",
  btnJoinFoundation: "Kubuela mu bulongolodi bua We Love Congo",

  // About Section
  aboutTitle: "Mulombodi wa Bilele udi upesha ditalala ne bukole",
  aboutDesc1: "Sa Majesté le Roi Kufulula (HRM King Kufulula) udi muenji wa bulongolodi bunene bua Isolele. Mulondi wa mianda wa dikema, mufundi wa mikanda ne mulami wa bilele bia kale, udi ufila muoyo wende bua kushintulula mushindu udi bantu ba pa buloba bamona bilele bia mu Afrika. Bu mudiye Mfumu wa kudi ba Pindi ne mulombodi udi musombele mu Amerike, udi ulongolola nshindamenu mukole munda mua mianda ya kale ne malu a mpa a ordinatere.",
  aboutMissionTitle: "Mudimu wa Isolele",
  aboutMissionDesc: "Kutumbisha bubanji, mianda ya kale, bikadilu ne mianda ya bunkalenga ya mu Afrika ku diambuluisha dia mikanda ya bimfuanyi ne bintu bia luse bia pa buloba bujima.",
  aboutResilienceTitle: "Ditaba dia Bukole",
  aboutResilienceDesc: "Luendu ludi luibaka kudi ditaba dikole, kushintulula njiwu ne bikandilu bua kulua ngakuilu wa bukole, buneme ne luse lua bantu bonso.",

  // Literary Works
  worksTitle: "Mikanda Inene ya Matumbishi",
  work1Title: "1. ZAIÏRE : Mfumu muana wa ku Kongo ne Kansolo ka lufu",
  work1Type: "Mushindu: Mukanda wa Bimfuanyi / Muanda wa dikema",
  work1Desc: "Luendu lua dikema ludi lutuandijila munda mua Kinshasa bua kuya too na ku mikalo ya mafumu a kale a munda mua bitupa bia nzambi. Mudimu ewu udi uleja bukole bua kansolo ka tshijila kadi ne bualu bua muoyo wa mu Afrika. Mudimu munene udibo batumbisha bua ditaba dia bilele bia kale.",
  work2Title: "2. WOLF OF CONGO : Mfumu muana wa mu Kinshasa",
  work2Type: "Mushindu: Mukanda wa mianda ya muoyo / Muanda wa muoyo ne Bulombodi",
  work2Desc: "Dibuela munda mua buana ne luendu lua Arnold Kufulula. Mukoleshibue kule na nzubu ya bufumu, munda mua bukole bua bupele, mukanda ewu udi uleja mudi dinemeka dia mikenji, kanyinganyinga kumpala kua dibenga dia malu ne kuakaja kuimpe kuenda kulombola muntu bua kukumbaja mudimu wende wa bunkalenga ne wa diambuluisha bantu.",

  // Impact Section
  impactTitle: "Diambuluisha ne Bulongolodi bua Luse",
  impactSubtitle: "Bulongolodi bua \"We Love Congo\"",
  impactIntro: "Dishintuluka kadiena anu munda mua mikanda kofundi to; didi mu bikadilu fuku nansha fuku. Ku diambuluisha dia bulongolodi bwende kabuyi bua bintu, Mfumu Kufulula udi wenza mudimu mukole :",
  impact1Title: "Diambuluisha kudi bafuishe",
  impact1Desc: "Diambuluisha dia mfranga ne bintu kudi bantu badi mu mvita mu Est wa RDC.",
  impact2Title: "Dikuatshisha dia bansonga",
  impact2Desc: "Malu a tulasa, dilonga dia midimu ya bianza bua bantu ba mu miaba eyi bikale ne dikuatshisha buabo nkayabo.",
  impact3Title: "Dijuka",
  impact3Desc: "Kupesha bansonga bimfuanyi biimpe bua bitabe bukole buabo bua kuenza bintu bimpi.",

  // Awards Section
  awardsTitle: "Tshitupa tshia Bifumu ne Netu",
  award1: "Indusa African Excellence (2025) | Ditumbisha dia bilele ne bulombodi bua mu Afrika.",
  award2: "My New York Magazine Feature (2025) | Ditaba dia pa buloba bujima bua mudimu wa Isolele.",
  award3: "Focus Congo Peace Maker (2024) | Tshitupa tshia buneme bua mudimu wa ditalala kudi bantu.",
  award4: "International Father’s Association (2023) | Dinemeka dia bualu bua mu kifuko ne kuakaja kuimpe.",

  // Contact
  contactTitle: "Buelayi mu Dijuka dia Bilele via mu Afrika",
  fieldFullName: "Dina Dijima / Bulongolodi",
  fieldEmail: "Email ya Mudimu",
  fieldMessage: "Mukanda / Lungenyi lua kuenza mudimu pamue",
  fieldSubmit: "Tuma Lungenyi lua wanyi mukanda",
  footerText: "© 2026 Kufulula & Isolele Ecosystem. Malu onso mbalama.",
  footerPower: "Muenza kudi dinanga dia Afrika. Kudi Bukavu, Kinshasa ne pa buloba bujima."
};
