export const sw = {
  // Original translation keys
  appName: "KUFULULA",
  heroBadge: "Soko Huria ya Biashara na Usalama wa Escrow",
  heroTitle: "Soko Ambalo Ulimwengu Ulisubiri. Badilishana Bila Mipaka. Dunia Moja. Jukwaa Moja.",
  heroSub: "Nunua kwa salama kupitia escrow ya Mobile Money na uthibitisho wa uso ya KYC.",
  searchPlaceholder: "Tafuta bidhaa, picha ya Lens, au Code QR...",
  categoryAll: "Mikusanyiko Yote",
  categoryElectronics: "Vifaa vya Umeme",
  categoryFood: "Chakula na Matunda",
  categoryFashion: "Mavazi na Vitenge",
  categoryHome: "Vyombo vya Ndani",
  categoryBooks: "Vitabu na Katuni",
  noProductFound: "Hakuna bidhaa inayolingana na ombi lako.",
  noProductSub: "Badilisha kichujio to omba msaada wa sauti na picha.",
  cartTitle: "Kikapu Chako cha Manunuzi",
  addToCart: "Weka Kwenye Kikapu",
  buyNow: "Lipia Maagizo Sikoyo kikawaida",
  negotiate: "Elewana Bei",
  share: "Shiriki na Wengi",
  like: "Pendezwa",
  comment: "Andika Maoni",
  commentsTitle: "Maoni kutoka kwa Jamii",
  writeComment: "Andika maoni ya kweli...",
  postComment: "Tuma Maoni",
  colorSelect: "Chagua rangi ya bidhaa:",
  angleSelect: "Pembe ya picha:",
  specifications: "Ufafanuzi kamili wa kiufundi",
  vendorLabel: "Muuzaji aliyeidhinishwa",
  stockLabel: "Kiasi kilichopo ghalani",
  priceLabel: "Hesabu ya bei",
  escrowBadge: "Dhamana ya Escrow ya Mobile Money",
  escrowActiveBadge: "Dhamana imewezeshwa",
  escrowStatusSecured: "Pesa ziko salama",
  kycVerificationRequired: "Uthibitisho wa KYC kwa sekunde moja unahitajika",
  backToShop: "Rudi Kwenye Orodha",
  settingsTitle: "Mipangilio ya Jinsi Web inavyoonekana",
  themeSelect: "Mandhari ya Rangi",
  fontSelect: "Muundo wa Herufi",
  currencyToggle: "Badilisha hesabu ya pesa",
  adminPortal: "Tovuti ya Usimamizi",
  voiceSearchListen: "Inasikiliza sasa... Taja jina la bidhaa yako",
  voiceSearchStop: "Akili Mnemba inachambua sauti yako...",
  lensTitle: "Google Lens & Akili Mnemba",
  lensScan: "Sogeza picha ya bidhaa au pakia faili ili kuitambua mara moja kwa msaada wa usaidizi wa Akili Mnemba...",
  negotiationTitle: "Majadiliano ya Bei na Ofa Mbadala",
  negotiateSubmit: "Tuma bei ninayotaka kulipia",
  negotiateCounter: "Majibu ya muuzaji",

  // Navigation
  navHome: "Mwanzo",
  navAbout: "Kuhusu Sisi",
  navWorks: "Kazi Zetu na Katuni",
  navImpact: "Misaada na Taasisi",
  navAwards: "Tuzo ya Heshima",
  navContact: "Mawasiliano",

  // Hero Section
  heroAuthorTitle: "S.M. MFALME KUFULULA",
  heroAuthorSub: "Mwenye Maono Anayefafanua Upya Hadithi ya Afrika",
  heroQuote: "Hadithi ya Afrika haipaswi kusimuliwa tena na watu baki. Tunatengeneza masimulizi yetu wenyewe ili kuangazia ulimwengu na kuhamasisha vizazi vijavyo.",
  heroSlogan: "Kugundua upya urithi wetu halisi, kusherehekea utu wetu, na kujenga mustakabali usio na mipaka kupitia nguvu ya maneno na sanaa za picha.",
  btnDiscoverWorks: "Gundua Kazi za Fasihi",
  btnJoinFoundation: "Jiunge na Taasisi ya We Love Congo",

  // About Section
  aboutTitle: "Kiongozi wa Kiutamaduni na mwana-Afrika Anayevutia",
  aboutDesc1: "Mtukufu Mfalme Kufulula (HRM King Kufulula) ni mwanzilishi wa jukwaa maarufu la Isolele. Msimulizi wa kipekee, mwandishi, na mlinzi wa mila, anatoa maisha yake kubadilisha mtazamo wa ulimwengu kuhusu utamaduni wa Afrika. Kama Mwana mfalme wa Wa-Pindi na kiongozi wa Kiafrika anayeishi Marekani, anajenga daraja imara kati ya historia ya mababu na usasa wa kidijiti.",
  aboutMissionTitle: "Wajibu wa Isolele",
  aboutMissionDesc: "Kusukuma mbele utajiri, hadithi za kale, maadili, na masimulizi huru ya Afrika kupitia katuni za kusisimua, riwaya za picha, na kazi za filamu za kiwango cha kimataifa.",
  aboutResilienceTitle: "Ustahimilivu kama Urithi",
  aboutResilienceDesc: "Safari iliyoundwa na ustahimilivu, ikibadilisha vikwazo na changamoto kuwa lugha ya nguvu, utu, na huruma ya pamoja.",

  // Literary Works
  worksTitle: "Kazi Kamili za Fasihi na Vitabu",
  work1Title: "1. ZAIÏRE : Mwana mfalme wa Kongo na Mkufu wa Majaliwa",
  work1Type: "Aina: Riwaya ya Picha / Hadithi ya Kale ya Kusisimua",
  work1Desc: "Safari ya kushangaza inayoanzia katikati ya jiji la Kinshasa na kuenea hadi mipaka ya falme za kale za kimizimu. Kazi hii ya kipekee inachunguza nguvu ya mkufu mtakatifu unaoshikilia siri za nguvu ya uzima ya Kiafrika. Kazi kubwa inayosifiwa kwa uaminifu wake kwa maadili ya kiroho ya mababu na kukuza mavazi ya jadi.",
  work2Title: "2. WOLF OF CONGO : Mwana mfalme wa Kinshasa",
  work2Type: "Aina: Kumbukumbu za Maisha / Hadithi ya Maisha na Uongozi",
  work2Desc: "Simulizi ya kusikitisha na ya kuvutia kuhusu utoto na safari ya Arnold Kufulula. Alilelewa mbali na anasa za kifalme, katikati ya shida za umaskini, kitabu hiki kinaonyesha jinsi nidhamu, uvumilivu mbele ya ucheleweshaji wa mifumo, na uadilifu unavyoweza kumwongoza mtu kuelekea kutimiza hatima yake ya kifalme na ya kibinadamu.",

  // Impact Section
  impactTitle: "Athari ya Kibinadamu na Taasisi",
  impactSubtitle: "Taasisi ya \"We Love Congo\"",
  impactIntro: "Mabadiliko hayafanyiki tu kwenye hadithi zilizoandikwa; yanaonekana katika matendo ya kila siku. Kupitia shirika lake lisilo la kifaida, Mfalme Kufulula anafanya kazi kwa bidii uwanjani:",
  impact1Title: "Msaada kwa Waathirika",
  impact1Desc: "Msaada wa moja kwa moja kwa watu walioathiriwa na vita mashariki mwa Jamhuri ya Kidemokrasia ya Kongo.",
  impact2Title: "Kujiwezesha",
  impact2Desc: "Mipango ya elimu, mafunzo ya kazi, na ukarabati ili kuruhusu jamii za mitaa kufanikiwa zenyewe.",
  impact3Title: "Kuinuka",
  impact3Desc: "Kuwapa vijana mifano bora ili waamini uwezo wao wa ubunifu na ujasiriamali.",

  // Awards Section
  awardsTitle: "Tuzo na Heshima",
  award1: "Indusa African Excellence (2025) | Kusherehekea ubora wa kiutamaduni na uongozi wa Kiafrika.",
  award2: "My New York Magazine Feature (2025) | Utambuzi wa kimataifa wa athari za mfumo wa Isolele.",
  award3: "Focus Congo Peace Maker (2024) | Tuzo ya kuheshimu vitendo halisi kwa ajili ya amani na ustawi wa jamii.",
  award4: "International Father’s Association (2023) | Heshima kwa maadili ya kifamilia, malezi na wema.",

  // Contact
  contactTitle: "Jiunge na Ufufuo wa Utamaduni wa Kiafrika",
  fieldFullName: "Jina Kamili / Taasisi",
  fieldEmail: "Barua Pepe ya Kazi",
  fieldMessage: "Ujumbe / Nia ya Ushirikiano",
  fieldSubmit: "Wasilisha Ombi la Ushirikiano",
  footerText: "© 2026 Kufulula & Isolele Ecosystem. Haki zote zimehifadhiwa.",
  footerPower: "Inoendeshwa na mapenzi kwa Afrika. Imeunganishwa kwa fahari kutoka Bukavu, Kinshasa na ulimwengu mzima."
};
